#!/usr/bin/env python
# -*- coding:utf-8 -*-

import json
import MySQLdb

def show_personal_information():
    json_data = {
        "error_code": 0,
        "data": {
            "telephone": "15262425192",
            "password": "qqqqqqq",
        }
    }
    res = {
        "error_code": 0,
        "data": []
    }
    telephone = json_data["data"]["telephone"]
    password = json_data["data"]["password"]
    db = MySQLdb.connect("47.101.217.136", "phd", "11111111", "software", charset='utf8')
    cursor = db.cursor(MySQLdb.cursors.DictCursor)
    sql = """select password 
            from user 
            where telephone= %s """
    try:
        cursor.execute(sql % telephone)
        results = cursor.fetchall()
    except:
        print("Error: unable to fecth data")
    db.close()
    #print (res)
    return json.dumps(res, ensure_ascii=False)


#注册
#!/usr/bin/env python
# -*- coding:utf-8 -*-

import json
import MySQLdb


def registe():
    json_data = {
        "error_code": 0,
        "data": {
             "telephone": "13107655128",
             "password": "qqqqqqq",
             "name": "有所谓",
             "sex": "男",
             "academy": "经管学院",
             "student_id": "071702432",
             "wechat_name": "sdees111",
             "head_link": "1"
        }
    }
    #print (json_data)
    telephone = json_data["data"]["telephone"]
    password = json_data["data"]["password"]
    name = json_data["data"]["name"]
    sex = json_data["data"]["sex"]
    academy = json_data["data"]["academy"]
    student_id = json_data["data"]["student_id"]
    wechat_name = json_data["data"]["wechat_name"]
    head_link = json_data["data"]["head_link"]

    db = MySQLdb.connect("47.101.217.136", "phd", "11111111", "software", charset='utf8')
    cursor = db.cursor()
    sql = """INSERT INTO user(wechat_name, head_link, name, telephone, sex, 
            academy, student_id, password)
            values(%s,%s,%s,%s,%s,%s,%s,%s)"""
    #print (json_data)
    try:
        # 执行sql语句
        cursor.execute(sql, (wechat_name, head_link, name, telephone, sex,
            academy, student_id, password))
        # 提交到数据库执行
        db.commit()
    except:
        # Rollback in case there is any error
        db.rollback()
        print ("error")

    # 关闭数据库连接
    db.close()
    res = {
        "error_code": 0,
        "data": {
            "result": "1",
        }
    }
    return json.dumps(res, ensure_ascii=False)
